name: Run Tests in my project every push on Github

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cd weekly_mission_4/refactoring
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3