name: Run Tests in my project every push on Github

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: |
        cd weekly_mission_4/refactoring
        npm install
    - name: Run Jest
      run: | 
        cd weekly_mission_4/refactoring
        stefanoeb/jest-action@1.0.3